import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/ui/shared/Navbar";
import { poppins } from "@/app/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <section className="mt-24 md:mt-32">{children}</section>
      </body>
    </html>
  );
}
